# Generated by Django 4.1.4 on 2022-12-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='sku')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('code', models.SlugField(max_length=255, verbose_name='code')),
                ('value_type', models.CharField(choices=[('string', 'string'), ('decimal', 'decimal')], max_length=10, verbose_name='value type')),
            ],
            options={
                'verbose_name': 'property object',
                'verbose_name_plural': 'properties objects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availibility', models.CharField(choices=[('in-stock', 'in-stock'), ('preorder', 'preorder'), ('coming-soon', 'coming-soon'), ('out-of-stock', 'out-of-stock'), ('out-of-production', 'out-of-production')], max_length=20, unique=True, verbose_name='availibility')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'ordering': ['availibility'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='value string')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='value decimal')),
                ('code', models.SlugField(max_length=255, verbose_name='code')),
                ('products', models.ManyToManyField(to='products.product')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.propertyobject')),
            ],
            options={
                'verbose_name': 'value',
                'verbose_name_plural': 'values',
                'ordering': ['value_string', 'value_decimal'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.status'),
        ),
    ]
